# Generated by Django 2.0.3 on 2018-03-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw', models.PositiveIntegerField(verbose_name='회차')),
                ('winning_number', models.PositiveSmallIntegerField(verbose_name='당첨번호')),
                ('is_bonus_number', models.BooleanField(verbose_name='보너스번호 유무')),
                ('group', models.CharField(choices=[('1~10', '1그룹(1~10)'), ('11~20', '2그룹(11~20)'), ('21~30', '3그룹(21~30)'), ('31~40', '4그룹(31~40)'), ('41~50', '5그룹(41~50)')], max_length=15, verbose_name='그룹')),
                ('odd_even', models.CharField(choices=[('odd', '홀수'), ('even', '짝수')], max_length=15, verbose_name='홀짝')),
                ('date', models.DateField(verbose_name='추첨일')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lottonumber',
            unique_together={('draw', 'winning_number')},
        ),
    ]
